[build]
  publish = "."
  command = "echo 'No build step required'"

[build.environment]
  NODE_VERSION = "18"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://rdv-news-api.vercel.app https://*.vercel.app https://api.airtable.com https://*.airtable.com https://hooks.slack.com https://api.allorigins.win https://cors-anywhere.herokuapp.com https://proxy.cors.sh https://corsproxy.io https://crossorigin.me;"
# Asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML files - no cache
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Development configuration
[dev]
  command = "npx http-server -p 3000"
  port = 3000
  publish = "."
  autoLaunch = true

# API redirects for future Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing for Airtable record IDs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200